environment: production
title: Andrew Juarez
email: andrew@andrewjuarez.com
description: Web and Graphic Design Portfolio of Andrew Juarez
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  drurez

# Build settings
markdown: kramdown
plugins:
  - jekyll-assets
  - breakpoint
  - susy
  - uglifier

# Asset Pipeline
assets:
  compress:
    css: true
    js: true
  digest: true
  sources:
    - _assets
    - _assets/scss
    - _assets/fonts
    - _assets/images
    - _assets/js


# Collections
collections:
  projects:
    output: true
    redirect: index.html
    permalink: :path/

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - README.md
